dist: xenial

sudo: true

services:
  - postgresql

language: python

python:
  - '3.7'

before_install:
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
  - chmod +x Miniconda3-latest-Linux-x86_64.sh
  - ./Miniconda3-latest-Linux-x86_64.sh -b

install:
  - pip install tox-travis tox-conda
  - mkdir RobotMissionIfc
  - pip install -U wheel setuptools
  - pip install codecov

script: tox

after_success: codecov

env:
  global:
    - PGPORT=5432
    - TRAVIS=TRAVIS
