dist: xenial

sudo: false

services:
  - postgresql

language: python

python:
  - '3.7'

before_install:
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
  - chmod +x Miniconda3-latest-Linux-x86_64.sh
  - ./Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda
  - cp test/config_test_pgsql.py robotmissions/config.py
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda install --yes pip
  - conda install --yes -c conda-forge ifcopenshell
  - ./scripts/install.sh

install:
  - pip install tox-travis tox-conda
  - pip install -U wheel setuptools
  - pip install codecov

script: tox

after_success: codecov

env:
  global:
    - PGPORT=5432
    - TRAVIS=TRAVIS
