dist: xenial

sudo: true

services:
  - postgresql

language: python

python:
  - '3.7'

before_install:
  - ./scripts/install.sh

install:
  - pip install -U wheel setuptools
  - pip install tox-travis tox-conda
  - pip install codecov

script: tox

after_success: codecov

env:
  global:
    - PGPORT=5432
    - TRAVIS=TRAVIS
