# Generated by Django 3.0.1 on 2020-02-03 18:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IFCModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('filePath', models.FilePathField(path='C:\\RobotMissionIfc\\')),
            ],
        ),
    ]
