# Generated by Django 3.0.1 on 2020-02-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ifc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ifcmodel',
            name='name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ifcmodel',
            name='filePath',
            field=models.FilePathField(path='C:/RobotMissionIfc/'),
        ),
    ]
