# Generated by Django 2.2.5 on 2020-02-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ifc', '0002_auto_20200203_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ifcmodel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
