# Generated by Django 2.2.5 on 2020-02-12 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ifc', '0003_auto_20200211_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotStatusModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rotation', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='RobotPositionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(max_length=100)),
                ('x', models.DecimalField(decimal_places=2, max_digits=20)),
                ('y', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ifc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifc.IfcModel')),
            ],
        ),
        migrations.CreateModel(
            name='RobotModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot.RobotPositionModel')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='robot.RobotStatusModel')),
            ],
        ),
    ]
