# Generated by Django 2.2.5 on 2020-02-11 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('ifc', '0003_auto_20200211_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeplacementMissionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_space', models.CharField(max_length=100)),
                ('end_space', models.CharField(max_length=100)),
                ('ifc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifc.IfcModel')),
            ],
        ),
    ]
