# Generated by Django 2.2.5 on 2020-02-11 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deplacementmissionmodel',
            name='floor',
            field=models.CharField(default='00_RDC', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deplacementmissionmodel',
            name='ifc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifc.IfcModel'),
        ),
    ]
