# Generated by Django 2.2.5 on 2020-02-12 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0002_auto_20200211_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deplacementmissionmodel',
            name='ifc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifc.IfcModel'),
        ),
    ]
